export const REMOVE_TRANSACTION = 'REMOVE_TRANSACTION';
export const EDIT_TRANSACTION = 'EDIT_TRANSACTION';
export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const CLEAR_TRANSACTION = 'CLEAR_TRANSACTION';